# - name: delete app directory
#   ansible.builtin.file:
#    path: "{{ app_location }}"
#    state: absent
#   # ignore_errors: yes cd

# - name: create app directory
#   ansible.builtin.file:
#     path: "{{ app_location }}"
#     state: directory

# - name: download and extract code
#   ansible.builtin.unarchive:
#     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip
#     dest: "{{ app_location }}"
#     remote_src: yes

# # - name: download the artifact from nexus
# #   ansible.builtin.unarchive:
# #     src: "http://{{ nexus_url }}/repository/{{ component }}/com/expense/{{ component }}/{{ appVersion }}/{{ component }}-{{ appVersion }}.zip"
# #     dest: "{{ app_location }}"
# #     remote_src: yes
- name: remove existing directory
  tags: 
  - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCAION }}" # backend folder is /app, frontend /usr/share/nginx/html
    state: absent

- name: create app directory
  tags: 
  - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCAION }}" # backend folder is /app, frontend /usr/share/nginx/html
    state: directory

- name: download app code
  tags: 
  - deployment
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip"
    dest: "{{ APP_LOCAION }}"
    remote_src: yes


# - name: download the artifact from nexus
#   ansible.builtin.unarchive:
#     src: "http://{{ nexus_url }}/repository/{{ component }}/com/expense/{{ component }}/{{ appVersion }}/{{ component }}-{{ appVersion }}.zip"
#     dest: "{{ app_location }}"
#     remote_src: yes    
    